
import React, { useState } from 'react';
import { Save, FileText } from 'lucide-react';

const DiagnosisWriter = ({ caseId }) => {
    const [diagnosis, setDiagnosis] = useState('');

    const handleSave = () => {
        if (!caseId) return;

        const timestamp = new Date().toLocaleString();
        const filename = `Diagnosis_${caseId}_${new Date().toISOString().slice(0, 10)}.txt`;

        const content = `MEDICAL DIAGNOSIS REPORT
----------------------------------------
Case ID: ${caseId}
Date: ${timestamp}
----------------------------------------

DOCTOR'S NOTES:
${diagnosis}

----------------------------------------
Generated by AI-ECG Assistant
`;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 flex flex-col h-full overflow-hidden">
            <div className="px-4 py-2 border-b border-slate-100 bg-slate-50 flex justify-between items-center shrink-0">
                <h3 className="font-bold text-slate-700 flex items-center gap-2 text-sm">
                    <FileText size={16} className="text-blue-500" /> Diagnosis Entry
                </h3>
                <button
                    onClick={handleSave}
                    disabled={!diagnosis.trim()}
                    className="flex items-center gap-2 px-3 py-1 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    <Save size={14} />
                    Save Report
                </button>
            </div>
            <div className="flex-1 p-2 bg-slate-50/30">
                <textarea
                    className="w-full h-full p-3 text-sm text-slate-700 bg-white border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-100 focus:border-blue-400 outline-none resize-none transition-all placeholder:text-slate-400"
                    placeholder="Enter clinical diagnosis and observations here..."
                    value={diagnosis}
                    onChange={(e) => setDiagnosis(e.target.value)}
                />
            </div>
        </div>
    );
};

export default DiagnosisWriter;
